import asyncio
import time

from lighter.signer_client import SignerClient, create_api_key
import pytest
from tests.constants import (
    L1_PRIVATE_KEY,
    API_PUBLIC_KEY,
    DEFAULT_MARKET_INDEX,
    ORDER_BASE_AMOUNT,
    SLIPPAGE_TEST_BASE_AMOUNT,
    API_KEY_INDEX,
    ACCOUNT_INDEX,
    API_KEY_PRIVATE_KEY,
    DEFAULT_NONCE,
)


def now_ms() -> int:
    return int(time.time() * 1_000)


def test_generate_api_key_via_native_signer():
    # Sanity: native signer can generate API/public keys
    priv, pub, err = create_api_key(seed="lighter-python-tests")
    assert err is None
    assert isinstance(priv, str) and len(priv) > 0
    assert isinstance(pub, str) and len(pub) > 0


def test_are_keys_equal_strips_0x_prefix():
    # Utility behavior: ignores 0x prefixes
    assert SignerClient.are_keys_equal("0xabcdef", "abcdef") is True
    assert SignerClient.are_keys_equal("abcdef", "0xabcdef") is True
    assert SignerClient.are_keys_equal("deadbeef", "feedbead") is False


@pytest.mark.asyncio
async def test_check_client_matches_remote_api_key(client: SignerClient):
    # Verifies the given (account, api_key) matches what's registered server-side
    err = client.check_client()
    assert err is None


@pytest.mark.asyncio
async def test_create_auth_token_success(client: SignerClient):
    # Auth token is generated by the native signer; ensure it looks valid
    auth, error = client.create_auth_token_with_expiry()
    assert error is None
    assert isinstance(auth, str) and len(auth) > 0


@pytest.mark.asyncio
async def test_create_then_cancel_limit_order(client: SignerClient):
    # Create a well-priced limit order based on the live best ask, then cancel it
    ob = await client.order_api.order_book_orders(DEFAULT_MARKET_INDEX, 1)
    if not ob.asks:
        pytest.skip("No asks in order book; cannot place a sell order on testnet")
    best_ask = int(ob.asks[0].price.replace(".", ""))
    price = int(best_ask * 1.01)  # 1% above best ask for a sell

    # ms since epoch for uniqueness
    client_order_index = now_ms()

    created_tx, resp, err = await client.create_order(
        market_index=DEFAULT_MARKET_INDEX,
        client_order_index=client_order_index,
        base_amount=ORDER_BASE_AMOUNT,
        price=price,
        is_ask=True,
        order_type=SignerClient.ORDER_TYPE_LIMIT,
        time_in_force=SignerClient.ORDER_TIME_IN_FORCE_GOOD_TILL_TIME,
        reduce_only=False,
    )
    assert err is None
    assert resp is not None and resp.code == 200

    # Give the backend a tick to register before canceling.
    # In a real-world scenario, you might want to poll for the order status
    # instead of using a fixed sleep.
    await asyncio.sleep(2)

    cancel_tx, cancel_resp, cancel_err = await client.cancel_order(
        market_index=DEFAULT_MARKET_INDEX,
        order_index=client_order_index,
    )
    assert cancel_err is None
    assert cancel_resp is not None and cancel_resp.code == 200


@pytest.mark.asyncio
async def test_switch_api_key(client: SignerClient):
    # Covers API key switching and nonce helper
    # switch_api_key returns None on success
    err = client.switch_api_key(API_KEY_INDEX)
    assert err is None


@pytest.mark.asyncio
async def test_get_api_key_nonce_helpers(client: SignerClient):
    # get_api_key_nonce echoes provided values if both supplied
    ak, nn = client.get_api_key_nonce(api_key_index=7, nonce=12345)
    assert ak == 7 and nn == 12345


@pytest.mark.skipif(not (L1_PRIVATE_KEY and API_PUBLIC_KEY), reason="L1 private key and API public key required")
@pytest.mark.asyncio
async def test_sign_change_api_key(client: SignerClient):
    # Pure signing (no network send): validates FFI wiring and payload preparation
    # Change API key requires a 0x-prefixed hex public key
    new_pub = API_PUBLIC_KEY if API_PUBLIC_KEY.startswith("0x") else f"0x{API_PUBLIC_KEY}"
    tx_type, tx_info, err = client.sign_change_api_key(L1_PRIVATE_KEY, new_pub, nonce=DEFAULT_NONCE)
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_transfer(client: SignerClient):
    # Pure signing (no network send): validates FFI wiring and payload preparation
    # Sign a transfer to our own account; memo must be exactly 32 bytes
    tx_type, tx_info, err = client.sign_transfer(
        eth_private_key=L1_PRIVATE_KEY or API_KEY_PRIVATE_KEY,
        to_account_index=ACCOUNT_INDEX,
        usdc_amount=1,
        fee=0,
        memo=("0" * 32),
        nonce=DEFAULT_NONCE,
    )
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_create_sub_account(client: SignerClient):
    # Pure signing (no network send): validates FFI wiring and payload preparation
    # Create sub-account signing
    tx_type, tx_info, err = client.sign_create_sub_account(nonce=DEFAULT_NONCE)
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_cancel_order(client: SignerClient):
    # Cancel order signing
    tx_type, tx_info, err = client.sign_cancel_order(market_index=DEFAULT_MARKET_INDEX, order_index=999999, nonce=DEFAULT_NONCE)
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_modify_order(client: SignerClient):
    # Modify order signing
    tx_type, tx_info, err = client.sign_modify_order(
        market_index=DEFAULT_MARKET_INDEX, order_index=999999, base_amount=10, price=12345, trigger_price=0, nonce=DEFAULT_NONCE
    )
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_cancel_all_orders(client: SignerClient):
    # Cancel all orders signing: some signer builds require nil timestamp for IMMEDIATE TIF
    tx_type, tx_info, err = client.sign_cancel_all_orders(
        time_in_force=SignerClient.CANCEL_ALL_TIF_IMMEDIATE, timestamp_ms=now_ms(), nonce=DEFAULT_NONCE
    )
    assert tx_type == SignerClient.TX_TYPE_CANCEL_ALL_ORDERS
    assert (err is None and isinstance(tx_info, str) and len(tx_info) > 0) or isinstance(err, str)


@pytest.mark.asyncio
async def test_sign_withdraw(client: SignerClient):
    # Withdraw signing (1 USDC)
    tx_type, tx_info, err = client.sign_withdraw(usdc_amount=1, nonce=DEFAULT_NONCE)
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_sign_update_leverage(client: SignerClient):
    # Update leverage signing
    tx_type, tx_info, err = client.sign_update_leverage(
        market_index=DEFAULT_MARKET_INDEX, fraction=5000, margin_mode=SignerClient.CROSS_MARGIN_MODE, nonce=DEFAULT_NONCE
    )
    assert err is None and isinstance(tx_info, str) and len(tx_info) > 0


@pytest.mark.asyncio
async def test_create_market_order_if_slippage_excessive_returns_error(client: SignerClient):
    # Intentionally request an excessive amount so matched_size < base_amount -> clear slippage error path
    created_tx, resp, err = await client.create_market_order_if_slippage(
        market_index=DEFAULT_MARKET_INDEX,
        client_order_index=now_ms(),
        base_amount=SLIPPAGE_TEST_BASE_AMOUNT,
        max_slippage=0.05,
        is_ask=True,
    )
    assert err is not None and "slippage" in err.lower()
    assert created_tx is None and resp is None


