# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ApprovedIntegrator(BaseModel):
    """
    ApprovedIntegrator
    """ # noqa: E501
    account_index: StrictInt
    name: StrictStr
    max_perps_taker_fee: StrictInt
    max_perps_maker_fee: StrictInt
    max_spot_taker_fee: StrictInt
    max_spot_maker_fee: StrictInt
    approval_expiry: StrictInt = Field(description=" Timestamp in milliseconds, after which the integrator is no longer approved")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["account_index", "name", "max_perps_taker_fee", "max_perps_maker_fee", "max_spot_taker_fee", "max_spot_maker_fee", "approval_expiry"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApprovedIntegrator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApprovedIntegrator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "account_index": obj.get("account_index"),
            "name": obj.get("name"),
            "max_perps_taker_fee": obj.get("max_perps_taker_fee"),
            "max_perps_maker_fee": obj.get("max_perps_maker_fee"),
            "max_spot_taker_fee": obj.get("max_spot_taker_fee"),
            "max_spot_maker_fee": obj.get("max_spot_maker_fee"),
            "approval_expiry": obj.get("approval_expiry")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


