# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DetailedAccountAccountTypeEnum(int, Enum):
    """
    Named values of DetailedAccount.account_type
    """

    """
    allowed enum values
    """
    Master = 0
    Sub = 1
    PublicPool = 2
    InsuranceFund = 3
    LighterStakingPool = 4
    TreasurySub = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DetailedAccountAccountTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


