# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ReferralTotals(BaseModel):
    """
    ReferralTotals
    """ # noqa: E501
    count: StrictInt
    volume: StrictStr
    free_maker_volume: StrictStr
    free_taker_volume: StrictStr
    non_free_maker_volume: StrictStr
    non_free_taker_volume: StrictStr
    maker_fees_paid: StrictStr
    taker_fees_paid: StrictStr
    total_referrals: StrictInt
    total_premium_referrals: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["count", "volume", "free_maker_volume", "free_taker_volume", "non_free_maker_volume", "non_free_taker_volume", "maker_fees_paid", "taker_fees_paid", "total_referrals", "total_premium_referrals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReferralTotals from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReferralTotals from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(**{
            "count": obj.get("count"),
            "volume": obj.get("volume"),
            "free_maker_volume": obj.get("free_maker_volume"),
            "free_taker_volume": obj.get("free_taker_volume"),
            "non_free_maker_volume": obj.get("non_free_maker_volume"),
            "non_free_taker_volume": obj.get("non_free_taker_volume"),
            "maker_fees_paid": obj.get("maker_fees_paid"),
            "taker_fees_paid": obj.get("taker_fees_paid"),
            "total_referrals": obj.get("total_referrals"),
            "total_premium_referrals": obj.get("total_premium_referrals")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


