# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReqGetTrades(BaseModel):
    """
    ReqGetTrades
    """ # noqa: E501
    auth: Optional[StrictStr] = None
    market_id: Optional[StrictInt] = None
    account_index: Optional[StrictInt] = None
    order_index: Optional[StrictInt] = None
    sort_by: StrictStr
    sort_dir: Optional[StrictStr] = 'desc'
    cursor: Optional[StrictStr] = None
    var_from: Optional[StrictInt] = Field(default=None, alias="from")
    ask_filter: Optional[StrictInt] = None
    limit: Annotated[int, Field(le=100, strict=True, ge=1)]
    role: Optional[StrictStr] = 'all'
    type: Optional[StrictStr] = 'all'
    aggregate: Optional[StrictBool] = False
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auth", "market_id", "account_index", "order_index", "sort_by", "sort_dir", "cursor", "from", "ask_filter", "limit", "role", "type", "aggregate"]

    @field_validator('sort_by')
    def sort_by_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['block_height', 'timestamp', 'trade_id']):
            raise ValueError("must be one of enum values ('block_height', 'timestamp', 'trade_id')")
        return value

    @field_validator('sort_dir')
    def sort_dir_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['desc']):
            raise ValueError("must be one of enum values ('desc')")
        return value

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['all', 'maker', 'taker']):
            raise ValueError("must be one of enum values ('all', 'maker', 'taker')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['all', 'trade', 'liquidation', 'deleverage', 'market-settlement']):
            raise ValueError("must be one of enum values ('all', 'trade', 'liquidation', 'deleverage', 'market-settlement')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReqGetTrades from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReqGetTrades from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth": obj.get("auth"),
            "market_id": obj.get("market_id"),
            "account_index": obj.get("account_index"),
            "order_index": obj.get("order_index"),
            "sort_by": obj.get("sort_by"),
            "sort_dir": obj.get("sort_dir") if obj.get("sort_dir") is not None else 'desc',
            "cursor": obj.get("cursor"),
            "from": obj.get("from"),
            "ask_filter": obj.get("ask_filter"),
            "limit": obj.get("limit"),
            "role": obj.get("role") if obj.get("role") is not None else 'all',
            "type": obj.get("type") if obj.get("type") is not None else 'all',
            "aggregate": obj.get("aggregate") if obj.get("aggregate") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


