# coding: utf-8

# flake8: noqa

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountApi",
    "AnnouncementApi",
    "BlockApi",
    "BridgeApi",
    "CandlestickApi",
    "FundingApi",
    "InfoApi",
    "NotificationApi",
    "OrderApi",
    "ReferralApi",
    "RootApi",
    "TokenlistApi",
    "TransactionApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Account",
    "AccountApiKeys",
    "AccountAsset",
    "AccountLimits",
    "AccountMarginStats",
    "AccountMarketStats",
    "AccountMetadata",
    "AccountMetadatas",
    "AccountPnL",
    "AccountPosition",
    "AccountStats",
    "AccountTradeStats",
    "Announcement",
    "Announcements",
    "ApiKey",
    "ApiToken",
    "ApprovedIntegrator",
    "Asset",
    "AssetDetails",
    "Block",
    "Blocks",
    "BridgeSupportedNetwork",
    "BridgeSupportedNetworks",
    "Candle",
    "Candles",
    "Candlestick",
    "Candlesticks",
    "ContractAddress",
    "CreateIntentAddressResp",
    "CurrentHeight",
    "Cursor",
    "DailyReturn",
    "Deposit",
    "DepositHistory",
    "DepositHistoryItem",
    "DetailedAccount",
    "DetailedAccounts",
    "DetailedCandlestick",
    "EnrichedTx",
    "ExchangeMetric",
    "ExchangeStats",
    "ExecuteStat",
    "ExportData",
    "Funding",
    "FundingRate",
    "FundingRates",
    "Fundings",
    "L1Metadata",
    "L1ProviderInfo",
    "Layer1BasicInfo",
    "LeaseEntry",
    "LeaseOptionEntry",
    "LiqTrade",
    "Liquidation",
    "LiquidationInfo",
    "LiquidationInfos",
    "MarketConfig",
    "NextNonce",
    "Order",
    "OrderBook",
    "OrderBookDepth",
    "OrderBookDetails",
    "OrderBookOrders",
    "OrderBookStats",
    "OrderBooks",
    "Orders",
    "PartnerStats",
    "PendingUnlock",
    "PerpsMarketStats",
    "PerpsOrderBookDetail",
    "PnLEntry",
    "PositionFunding",
    "PositionFundings",
    "PriceLevel",
    "PublicPoolInfo",
    "PublicPoolMetadata",
    "PublicPoolShare",
    "Referral",
    "ReferralCode",
    "ReferralPointEntry",
    "ReferralPoints",
    "ReqExportData",
    "ReqGetAccount",
    "ReqGetAccountActiveOrders",
    "ReqGetAccountApiKeys",
    "ReqGetAccountByL1Address",
    "ReqGetAccountInactiveOrders",
    "ReqGetAccountLimits",
    "ReqGetAccountMetadata",
    "ReqGetAccountPnL",
    "ReqGetAccountTxs",
    "ReqGetBlock",
    "ReqGetBlockTxs",
    "ReqGetByAccount",
    "ReqGetCandlesticks",
    "ReqGetDepositHistory",
    "ReqGetFastWithdrawInfo",
    "ReqGetFundings",
    "ReqGetL1Metadata",
    "ReqGetL1Tx",
    "ReqGetLatestDeposit",
    "ReqGetLiquidationInfos",
    "ReqGetMakerOnlyApiKeys",
    "ReqGetNextNonce",
    "ReqGetOrderBookDetails",
    "ReqGetOrderBookOrders",
    "ReqGetOrderBooks",
    "ReqGetPositionFunding",
    "ReqGetPublicPoolsMetadata",
    "ReqGetRangeWithCursor",
    "ReqGetRangeWithIndex",
    "ReqGetRangeWithIndexSortable",
    "ReqGetRecentTrades",
    "ReqGetReferralPoints",
    "ReqGetTrades",
    "ReqGetTransferFeeInfo",
    "ReqGetTransferHistory",
    "ReqGetTx",
    "ReqGetWithdrawHistory",
    "ReqSetAccountMetadata",
    "RespChangeAccountTier",
    "RespGetApiTokens",
    "RespGetExchangeMetrics",
    "RespGetExecuteStats",
    "RespGetFastBridgeInfo",
    "RespGetFastwithdrawalInfo",
    "RespGetLeaseOptions",
    "RespGetLeases",
    "RespGetMakerOnlyApiKeys",
    "RespPostApiToken",
    "RespPublicPoolsMetadata",
    "RespRevokeApiToken",
    "RespSendTx",
    "RespSendTxBatch",
    "RespSetMakerOnlyApiKeys",
    "RespUpdateKickback",
    "RespUpdateReferralCode",
    "RespWithdrawalDelay",
    "ResultCode",
    "RiskInfo",
    "RiskParameters",
    "SharePrice",
    "SimpleOrder",
    "SlippageResult",
    "SpotAvgEntryPrice",
    "SpotMarketStats",
    "SpotOrderBookDetail",
    "Status",
    "Strategy",
    "SubAccounts",
    "SystemConfig",
    "Ticker",
    "Token",
    "TokenList",
    "Trade",
    "TradeStats",
    "Trades",
    "TransferFeeInfo",
    "TransferHistory",
    "TransferHistoryItem",
    "Tx",
    "TxHash",
    "TxHashes",
    "Txs",
    "UserReferrals",
    "ValidatorInfo",
    "WithdrawHistory",
    "WithdrawHistoryItem",
    "ZkLighterInfo",
]

# import apis into sdk package
from lighter.api.account_api import AccountApi as AccountApi
from lighter.api.announcement_api import AnnouncementApi as AnnouncementApi
from lighter.api.block_api import BlockApi as BlockApi
from lighter.api.bridge_api import BridgeApi as BridgeApi
from lighter.api.candlestick_api import CandlestickApi as CandlestickApi
from lighter.api.funding_api import FundingApi as FundingApi
from lighter.api.info_api import InfoApi as InfoApi
from lighter.api.notification_api import NotificationApi as NotificationApi
from lighter.api.order_api import OrderApi as OrderApi
from lighter.api.referral_api import ReferralApi as ReferralApi
from lighter.api.root_api import RootApi as RootApi
from lighter.api.tokenlist_api import TokenlistApi as TokenlistApi
from lighter.api.transaction_api import TransactionApi as TransactionApi

# import ApiClient
from lighter.api_response import ApiResponse as ApiResponse
from lighter.api_client import ApiClient as ApiClient
from lighter.configuration import Configuration as Configuration
from lighter.exceptions import OpenApiException as OpenApiException
from lighter.exceptions import ApiTypeError as ApiTypeError
from lighter.exceptions import ApiValueError as ApiValueError
from lighter.exceptions import ApiKeyError as ApiKeyError
from lighter.exceptions import ApiAttributeError as ApiAttributeError
from lighter.exceptions import ApiException as ApiException

# import models into sdk package
from lighter.models.account import Account as Account
from lighter.models.account_api_keys import AccountApiKeys as AccountApiKeys
from lighter.models.account_asset import AccountAsset as AccountAsset
from lighter.models.account_limits import AccountLimits as AccountLimits
from lighter.models.account_margin_stats import AccountMarginStats as AccountMarginStats
from lighter.models.account_market_stats import AccountMarketStats as AccountMarketStats
from lighter.models.account_metadata import AccountMetadata as AccountMetadata
from lighter.models.account_metadatas import AccountMetadatas as AccountMetadatas
from lighter.models.account_pn_l import AccountPnL as AccountPnL
from lighter.models.account_position import AccountPosition as AccountPosition
from lighter.models.account_stats import AccountStats as AccountStats
from lighter.models.account_trade_stats import AccountTradeStats as AccountTradeStats
from lighter.models.announcement import Announcement as Announcement
from lighter.models.announcements import Announcements as Announcements
from lighter.models.api_key import ApiKey as ApiKey
from lighter.models.api_token import ApiToken as ApiToken
from lighter.models.approved_integrator import ApprovedIntegrator as ApprovedIntegrator
from lighter.models.asset import Asset as Asset
from lighter.models.asset_details import AssetDetails as AssetDetails
from lighter.models.block import Block as Block
from lighter.models.blocks import Blocks as Blocks
from lighter.models.bridge_supported_network import BridgeSupportedNetwork as BridgeSupportedNetwork
from lighter.models.bridge_supported_networks import BridgeSupportedNetworks as BridgeSupportedNetworks
from lighter.models.candle import Candle as Candle
from lighter.models.candles import Candles as Candles
from lighter.models.candlestick import Candlestick as Candlestick
from lighter.models.candlesticks import Candlesticks as Candlesticks
from lighter.models.contract_address import ContractAddress as ContractAddress
from lighter.models.create_intent_address_resp import CreateIntentAddressResp as CreateIntentAddressResp
from lighter.models.current_height import CurrentHeight as CurrentHeight
from lighter.models.cursor import Cursor as Cursor
from lighter.models.daily_return import DailyReturn as DailyReturn
from lighter.models.deposit import Deposit as Deposit
from lighter.models.deposit_history import DepositHistory as DepositHistory
from lighter.models.deposit_history_item import DepositHistoryItem as DepositHistoryItem
from lighter.models.detailed_account import DetailedAccount as DetailedAccount
from lighter.models.detailed_accounts import DetailedAccounts as DetailedAccounts
from lighter.models.detailed_candlestick import DetailedCandlestick as DetailedCandlestick
from lighter.models.enriched_tx import EnrichedTx as EnrichedTx
from lighter.models.exchange_metric import ExchangeMetric as ExchangeMetric
from lighter.models.exchange_stats import ExchangeStats as ExchangeStats
from lighter.models.execute_stat import ExecuteStat as ExecuteStat
from lighter.models.export_data import ExportData as ExportData
from lighter.models.funding import Funding as Funding
from lighter.models.funding_rate import FundingRate as FundingRate
from lighter.models.funding_rates import FundingRates as FundingRates
from lighter.models.fundings import Fundings as Fundings
from lighter.models.l1_metadata import L1Metadata as L1Metadata
from lighter.models.l1_provider_info import L1ProviderInfo as L1ProviderInfo
from lighter.models.layer1_basic_info import Layer1BasicInfo as Layer1BasicInfo
from lighter.models.lease_entry import LeaseEntry as LeaseEntry
from lighter.models.lease_option_entry import LeaseOptionEntry as LeaseOptionEntry
from lighter.models.liq_trade import LiqTrade as LiqTrade
from lighter.models.liquidation import Liquidation as Liquidation
from lighter.models.liquidation_info import LiquidationInfo as LiquidationInfo
from lighter.models.liquidation_infos import LiquidationInfos as LiquidationInfos
from lighter.models.market_config import MarketConfig as MarketConfig
from lighter.models.next_nonce import NextNonce as NextNonce
from lighter.models.order import Order as Order
from lighter.models.order_book import OrderBook as OrderBook
from lighter.models.order_book_depth import OrderBookDepth as OrderBookDepth
from lighter.models.order_book_details import OrderBookDetails as OrderBookDetails
from lighter.models.order_book_orders import OrderBookOrders as OrderBookOrders
from lighter.models.order_book_stats import OrderBookStats as OrderBookStats
from lighter.models.order_books import OrderBooks as OrderBooks
from lighter.models.orders import Orders as Orders
from lighter.models.partner_stats import PartnerStats as PartnerStats
from lighter.models.pending_unlock import PendingUnlock as PendingUnlock
from lighter.models.perps_market_stats import PerpsMarketStats as PerpsMarketStats
from lighter.models.perps_order_book_detail import PerpsOrderBookDetail as PerpsOrderBookDetail
from lighter.models.pn_l_entry import PnLEntry as PnLEntry
from lighter.models.position_funding import PositionFunding as PositionFunding
from lighter.models.position_fundings import PositionFundings as PositionFundings
from lighter.models.price_level import PriceLevel as PriceLevel
from lighter.models.public_pool_info import PublicPoolInfo as PublicPoolInfo
from lighter.models.public_pool_metadata import PublicPoolMetadata as PublicPoolMetadata
from lighter.models.public_pool_share import PublicPoolShare as PublicPoolShare
from lighter.models.referral import Referral as Referral
from lighter.models.referral_code import ReferralCode as ReferralCode
from lighter.models.referral_point_entry import ReferralPointEntry as ReferralPointEntry
from lighter.models.referral_points import ReferralPoints as ReferralPoints
from lighter.models.req_export_data import ReqExportData as ReqExportData
from lighter.models.req_get_account import ReqGetAccount as ReqGetAccount
from lighter.models.req_get_account_active_orders import ReqGetAccountActiveOrders as ReqGetAccountActiveOrders
from lighter.models.req_get_account_api_keys import ReqGetAccountApiKeys as ReqGetAccountApiKeys
from lighter.models.req_get_account_by_l1_address import ReqGetAccountByL1Address as ReqGetAccountByL1Address
from lighter.models.req_get_account_inactive_orders import ReqGetAccountInactiveOrders as ReqGetAccountInactiveOrders
from lighter.models.req_get_account_limits import ReqGetAccountLimits as ReqGetAccountLimits
from lighter.models.req_get_account_metadata import ReqGetAccountMetadata as ReqGetAccountMetadata
from lighter.models.req_get_account_pn_l import ReqGetAccountPnL as ReqGetAccountPnL
from lighter.models.req_get_account_txs import ReqGetAccountTxs as ReqGetAccountTxs
from lighter.models.req_get_block import ReqGetBlock as ReqGetBlock
from lighter.models.req_get_block_txs import ReqGetBlockTxs as ReqGetBlockTxs
from lighter.models.req_get_by_account import ReqGetByAccount as ReqGetByAccount
from lighter.models.req_get_candlesticks import ReqGetCandlesticks as ReqGetCandlesticks
from lighter.models.req_get_deposit_history import ReqGetDepositHistory as ReqGetDepositHistory
from lighter.models.req_get_fast_withdraw_info import ReqGetFastWithdrawInfo as ReqGetFastWithdrawInfo
from lighter.models.req_get_fundings import ReqGetFundings as ReqGetFundings
from lighter.models.req_get_l1_metadata import ReqGetL1Metadata as ReqGetL1Metadata
from lighter.models.req_get_l1_tx import ReqGetL1Tx as ReqGetL1Tx
from lighter.models.req_get_latest_deposit import ReqGetLatestDeposit as ReqGetLatestDeposit
from lighter.models.req_get_liquidation_infos import ReqGetLiquidationInfos as ReqGetLiquidationInfos
from lighter.models.req_get_maker_only_api_keys import ReqGetMakerOnlyApiKeys as ReqGetMakerOnlyApiKeys
from lighter.models.req_get_next_nonce import ReqGetNextNonce as ReqGetNextNonce
from lighter.models.req_get_order_book_details import ReqGetOrderBookDetails as ReqGetOrderBookDetails
from lighter.models.req_get_order_book_orders import ReqGetOrderBookOrders as ReqGetOrderBookOrders
from lighter.models.req_get_order_books import ReqGetOrderBooks as ReqGetOrderBooks
from lighter.models.req_get_position_funding import ReqGetPositionFunding as ReqGetPositionFunding
from lighter.models.req_get_public_pools_metadata import ReqGetPublicPoolsMetadata as ReqGetPublicPoolsMetadata
from lighter.models.req_get_range_with_cursor import ReqGetRangeWithCursor as ReqGetRangeWithCursor
from lighter.models.req_get_range_with_index import ReqGetRangeWithIndex as ReqGetRangeWithIndex
from lighter.models.req_get_range_with_index_sortable import ReqGetRangeWithIndexSortable as ReqGetRangeWithIndexSortable
from lighter.models.req_get_recent_trades import ReqGetRecentTrades as ReqGetRecentTrades
from lighter.models.req_get_referral_points import ReqGetReferralPoints as ReqGetReferralPoints
from lighter.models.req_get_trades import ReqGetTrades as ReqGetTrades
from lighter.models.req_get_transfer_fee_info import ReqGetTransferFeeInfo as ReqGetTransferFeeInfo
from lighter.models.req_get_transfer_history import ReqGetTransferHistory as ReqGetTransferHistory
from lighter.models.req_get_tx import ReqGetTx as ReqGetTx
from lighter.models.req_get_withdraw_history import ReqGetWithdrawHistory as ReqGetWithdrawHistory
from lighter.models.req_set_account_metadata import ReqSetAccountMetadata as ReqSetAccountMetadata
from lighter.models.resp_change_account_tier import RespChangeAccountTier as RespChangeAccountTier
from lighter.models.resp_get_api_tokens import RespGetApiTokens as RespGetApiTokens
from lighter.models.resp_get_exchange_metrics import RespGetExchangeMetrics as RespGetExchangeMetrics
from lighter.models.resp_get_execute_stats import RespGetExecuteStats as RespGetExecuteStats
from lighter.models.resp_get_fast_bridge_info import RespGetFastBridgeInfo as RespGetFastBridgeInfo
from lighter.models.resp_get_fastwithdrawal_info import RespGetFastwithdrawalInfo as RespGetFastwithdrawalInfo
from lighter.models.resp_get_lease_options import RespGetLeaseOptions as RespGetLeaseOptions
from lighter.models.resp_get_leases import RespGetLeases as RespGetLeases
from lighter.models.resp_get_maker_only_api_keys import RespGetMakerOnlyApiKeys as RespGetMakerOnlyApiKeys
from lighter.models.resp_post_api_token import RespPostApiToken as RespPostApiToken
from lighter.models.resp_public_pools_metadata import RespPublicPoolsMetadata as RespPublicPoolsMetadata
from lighter.models.resp_revoke_api_token import RespRevokeApiToken as RespRevokeApiToken
from lighter.models.resp_send_tx import RespSendTx as RespSendTx
from lighter.models.resp_send_tx_batch import RespSendTxBatch as RespSendTxBatch
from lighter.models.resp_set_maker_only_api_keys import RespSetMakerOnlyApiKeys as RespSetMakerOnlyApiKeys
from lighter.models.resp_update_kickback import RespUpdateKickback as RespUpdateKickback
from lighter.models.resp_update_referral_code import RespUpdateReferralCode as RespUpdateReferralCode
from lighter.models.resp_withdrawal_delay import RespWithdrawalDelay as RespWithdrawalDelay
from lighter.models.result_code import ResultCode as ResultCode
from lighter.models.risk_info import RiskInfo as RiskInfo
from lighter.models.risk_parameters import RiskParameters as RiskParameters
from lighter.models.share_price import SharePrice as SharePrice
from lighter.models.simple_order import SimpleOrder as SimpleOrder
from lighter.models.slippage_result import SlippageResult as SlippageResult
from lighter.models.spot_avg_entry_price import SpotAvgEntryPrice as SpotAvgEntryPrice
from lighter.models.spot_market_stats import SpotMarketStats as SpotMarketStats
from lighter.models.spot_order_book_detail import SpotOrderBookDetail as SpotOrderBookDetail
from lighter.models.status import Status as Status
from lighter.models.strategy import Strategy as Strategy
from lighter.models.sub_accounts import SubAccounts as SubAccounts
from lighter.models.system_config import SystemConfig as SystemConfig
from lighter.models.ticker import Ticker as Ticker
from lighter.models.token import Token as Token
from lighter.models.token_list import TokenList as TokenList
from lighter.models.trade import Trade as Trade
from lighter.models.trade_stats import TradeStats as TradeStats
from lighter.models.trades import Trades as Trades
from lighter.models.transfer_fee_info import TransferFeeInfo as TransferFeeInfo
from lighter.models.transfer_history import TransferHistory as TransferHistory
from lighter.models.transfer_history_item import TransferHistoryItem as TransferHistoryItem
from lighter.models.tx import Tx as Tx
from lighter.models.tx_hash import TxHash as TxHash
from lighter.models.tx_hashes import TxHashes as TxHashes
from lighter.models.txs import Txs as Txs
from lighter.models.user_referrals import UserReferrals as UserReferrals
from lighter.models.validator_info import ValidatorInfo as ValidatorInfo
from lighter.models.withdraw_history import WithdrawHistory as WithdrawHistory
from lighter.models.withdraw_history_item import WithdrawHistoryItem as WithdrawHistoryItem
from lighter.models.zk_lighter_info import ZkLighterInfo as ZkLighterInfo
from lighter.ws_client import WsClient
from lighter.signer_client import SignerClient, create_api_key
